/**
 * P4-11 · the sign atlas manifest.
 *
 * The manifest is GENERATED by tools/build-sign-atlas.py and imported as a module, so these guard
 * the contract between the two: cell order, UV correctness, and the fact that the page is sized to
 * its content. UASTC is fixed-rate — an empty cell costs exactly as much VRAM as a full one — so an
 * oversized page is not free headroom, it is silent waste on the one budget with none to spare.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import cells from '../src/map/signage/signAtlasCells.js';

test('every cell has a unique name and a unique slot', () => {
  const names = new Set(), slots = new Set();
  for (const c of cells.cells) {
    assert.equal(names.has(c.name), false, `duplicate name ${c.name}`);
    assert.equal(slots.has(c.cell), false, `duplicate slot ${c.cell}`);
    names.add(c.name); slots.add(c.cell);
  }
});

test('UVs are inside the page, correctly sized, and V is bottom-up', () => {
  const uw = cells.cell / (cells.cols * cells.cell);
  const vh = cells.cell / (cells.rows * cells.cell);
  for (const c of cells.cells) {
    const [u0, v0, u1, v1] = c.uv;
    assert.ok(u0 >= 0 && u1 <= 1 && v0 >= 0 && v1 <= 1, `${c.name} UVs out of range`);
    assert.ok(Math.abs((u1 - u0) - uw) < 1e-9, `${c.name} wrong U extent`);
    assert.ok(Math.abs((v1 - v0) - vh) < 1e-9, `${c.name} wrong V extent`);
    // Row 0 must sit at the TOP of the image, which in bottom-up V means the HIGHEST v.
    const row = Math.floor(c.cell / cells.cols);
    const expectedV1 = 1 - row * vh;
    assert.ok(Math.abs(v1 - expectedV1) < 1e-9,
      `${c.name} row ${row}: V is flipped — v1 ${v1} vs expected ${expectedV1}`);
  }
});

test('the page is sized to its content, with headroom but not waste', () => {
  const capacity = cells.cols * cells.rows;
  const used = cells.cells.length;
  assert.ok(used <= capacity, 'more cells than slots');
  // Room to grow for P4-12/P4-13, but not a page that is mostly empty.
  assert.ok(used / capacity > 0.5,
    `only ${used}/${capacity} cells used — UASTC is fixed-rate, so the empty ones cost full VRAM`);
});

test('the cells P4-12 and P4-13 depend on are present', () => {
  // These are named in the plan as their producers, so a rename here breaks a downstream ticket
  // silently — the sign would just not be found.
  const have = new Set(cells.cells.map((c) => c.name));
  for (const need of ['plate_white', 'arrow_straight', 'arrow_left', 'arrow_right',
                      'speed_30', 'speed_50', 'stop', 'yield',
                      'pharmacy_cross', 'metro_roundel']) {
    assert.ok(have.has(need), `missing cell '${need}'`);
  }
});

test('the manifest points at a KTX2, not a PNG', () => {
  // The PNG is an intermediate. Shipping it would decompress to RGBA on upload — 10.66 MB instead
  // of 2.67 MB for this page — which saves download size and nothing that matters.
  assert.match(cells.texture, /\.ktx2$/);
});
