// GENERATED by tools/build-bush-atlas.py — do not edit by hand.
// Re-run the tool after changing SPECIES or any source plate.
export default {
  "cell": 512,
  "cols": 3,
  "rows": 2,
  "normalizeVersion": 2,
  "species": [
    {
      "name": "lentisc",
      "cell": 0,
      "note": "Pistacia lentiscus - the defining Collserola scrub",
      "heightM": 1.2,
      "canopyM": 1.4,
      "uv": [
        0.0,
        0.5,
        0.333333,
        0.5
      ],
      "trunkBase": [
        0.5,
        0.9844
      ],
      "aspect": 1.3191,
      "contentUV": [
        0.005208,
        0.507812,
        0.322917,
        0.367188
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "foliage_leaf",
        "anchor": "#6E7A55",
        "snapAlpha": 0.35,
        "LStar": 45.0,
        "CStar": 20.6,
        "nearestAnchor": "P9_platanus_green",
        "deltaE2000": 4.33,
        "gate4Pass": true,
        "normalMeanXY": 0.275,
        "normalBandPass": true,
        "rallyClipPct": 0.426
      }
    },
    {
      "name": "rosemary",
      "cell": 1,
      "note": "Rosmarinus officinalis - dry hillside and verge",
      "heightM": 1.0,
      "canopyM": 0.9,
      "uv": [
        0.333333,
        0.5,
        0.333333,
        0.5
      ],
      "trunkBase": [
        0.5,
        0.9844
      ],
      "aspect": 1.029,
      "contentUV": [
        0.338542,
        0.507812,
        0.322917,
        0.470703
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "foliage_leaf",
        "anchor": "#6E7A55",
        "snapAlpha": 0.35,
        "LStar": 45.0,
        "CStar": 20.5,
        "nearestAnchor": "P9_platanus_green",
        "deltaE2000": 4.53,
        "gate4Pass": true,
        "normalMeanXY": 0.275,
        "normalBandPass": true,
        "rallyClipPct": 7.553
      }
    },
    {
      "name": "kermes_oak",
      "cell": 2,
      "note": "Quercus coccifera - spiny hillside scrub",
      "heightM": 1.3,
      "canopyM": 1.6,
      "uv": [
        0.666667,
        0.5,
        0.333333,
        0.5
      ],
      "trunkBase": [
        0.5,
        0.9844
      ],
      "aspect": 1.2751,
      "contentUV": [
        0.671875,
        0.507812,
        0.322917,
        0.379883
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "foliage_leaf",
        "anchor": "#6E7A55",
        "snapAlpha": 0.35,
        "LStar": 45.0,
        "CStar": 20.6,
        "nearestAnchor": "P9_platanus_green",
        "deltaE2000": 4.34,
        "gate4Pass": true,
        "normalMeanXY": 0.275,
        "normalBandPass": true,
        "rallyClipPct": 7.15
      }
    },
    {
      "name": "pittosporum",
      "cell": 3,
      "note": "Pittosporum tobira - the Barcelona street shrub",
      "heightM": 1.1,
      "canopyM": 1.3,
      "uv": [
        0.0,
        0.0,
        0.333333,
        0.5
      ],
      "trunkBase": [
        0.5,
        0.9844
      ],
      "aspect": 1.3478,
      "contentUV": [
        0.005208,
        0.007812,
        0.322917,
        0.359375
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "foliage_leaf",
        "anchor": "#6E7A55",
        "snapAlpha": 0.35,
        "LStar": 45.0,
        "CStar": 20.7,
        "nearestAnchor": "P9_platanus_green",
        "deltaE2000": 4.49,
        "gate4Pass": true,
        "normalMeanXY": 0.275,
        "normalBandPass": true,
        "rallyClipPct": 0.006
      }
    },
    {
      "name": "box_hedge",
      "cell": 4,
      "note": "Clipped Buxus - formal plaza and garden edging",
      "heightM": 0.8,
      "canopyM": 1.2,
      "uv": [
        0.333333,
        0.0,
        0.333333,
        0.5
      ],
      "trunkBase": [
        0.5,
        0.9844
      ],
      "aspect": 1.6052,
      "contentUV": [
        0.338542,
        0.007812,
        0.322917,
        0.301758
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "foliage_leaf",
        "anchor": "#6E7A55",
        "snapAlpha": 0.35,
        "LStar": 45.0,
        "CStar": 20.7,
        "nearestAnchor": "P9_platanus_green",
        "deltaE2000": 4.32,
        "gate4Pass": true,
        "normalMeanXY": 0.275,
        "normalBandPass": true,
        "rallyClipPct": 0.0
      }
    },
    {
      "name": "chamaerops",
      "cell": 5,
      "note": "Chamaerops humilis - the native Catalan dwarf fan palm",
      "heightM": 1.5,
      "canopyM": 1.5,
      "uv": [
        0.666667,
        0.0,
        0.333333,
        0.5
      ],
      "trunkBase": [
        0.5,
        0.9844
      ],
      "aspect": 1.1508,
      "contentUV": [
        0.671875,
        0.007812,
        0.322917,
        0.420898
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "foliage_leaf",
        "anchor": "#6E7A55",
        "snapAlpha": 0.35,
        "LStar": 45.0,
        "CStar": 20.3,
        "nearestAnchor": "P9_platanus_green",
        "deltaE2000": 4.4,
        "gate4Pass": true,
        "normalMeanXY": 0.275,
        "normalBandPass": true,
        "rallyClipPct": 6.684
      }
    }
  ]
};
