// GENERATED by tools/build-facade-layers.py — do not edit by hand.
export default {
  "layerWidthM": 8.0,
  "layerHeightM": 8.0,
  "size": 1024,
  "texelsPerM": 128.0,
  "normalizeVersion": 2,
  "layers": [
    {
      "name": "residential_cream",
      "index": 0,
      "surfaceClass": "facade",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "facade",
        "anchors": [
          "P1_eixample_cream",
          "P2_ochre_sand"
        ],
        "tileRaw": 2.36,
        "tileRatio": 0.002,
        "tileRoll": [
          1079,
          336
        ],
        "tileVerifyPass": true,
        "LStar": 74.0,
        "CStar": 12.2,
        "nearestAnchor": "P2_ochre_sand",
        "deltaE2000": 5.0,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 140.6,
        "grainBandPass": false,
        "windowFrac": 20.7,
        "notPlasterFrac": 22.0,
        "rallyClipPct": 0.0
      }
    },
    {
      "name": "residential_ochre",
      "index": 1,
      "surfaceClass": "facade",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "facade",
        "anchors": [
          "P2_ochre_sand",
          "P1_eixample_cream"
        ],
        "tileRaw": 0.49,
        "tileRatio": 0.0,
        "tileRoll": [
          906,
          1165
        ],
        "tileVerifyPass": true,
        "LStar": 74.1,
        "CStar": 12.2,
        "nearestAnchor": "P2_ochre_sand",
        "deltaE2000": 5.11,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 140.6,
        "grainBandPass": false,
        "windowFrac": 20.3,
        "notPlasterFrac": 31.4,
        "rallyClipPct": 0.388
      }
    },
    {
      "name": "residential_rose",
      "index": 2,
      "surfaceClass": "facade",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "facade",
        "anchors": [
          "P3_modernisme_rose",
          "P4_teula_clay"
        ],
        "tileRaw": 0.5,
        "tileRatio": 0.002,
        "tileRoll": [
          1151,
          140
        ],
        "tileVerifyPass": true,
        "LStar": 73.9,
        "CStar": 12.2,
        "nearestAnchor": "P3_modernisme_rose",
        "deltaE2000": 11.33,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 171.9,
        "grainBandPass": false,
        "windowFrac": 15.3,
        "notPlasterFrac": 40.2,
        "rallyClipPct": 3.375
      }
    },
    {
      "name": "residential_grey",
      "index": 3,
      "surfaceClass": "facade",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "facade",
        "anchors": [
          "P6_panot_grey",
          "P2_ochre_sand"
        ],
        "tileRaw": 1.07,
        "tileRatio": 0.0,
        "tileRoll": [
          950,
          549
        ],
        "tileVerifyPass": true,
        "LStar": 74.0,
        "CStar": 12.0,
        "nearestAnchor": "P6_panot_grey",
        "deltaE2000": 4.88,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 78.1,
        "grainBandPass": false,
        "windowFrac": 4.7,
        "notPlasterFrac": 7.0,
        "rallyClipPct": 0.084
      }
    },
    {
      "name": "residential_oldtown",
      "index": 4,
      "surfaceClass": "facade",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "facade",
        "anchors": [
          "P1_eixample_cream",
          "P2_ochre_sand"
        ],
        "tileRaw": 15.65,
        "tileRatio": 0.0,
        "tileRoll": [
          1128,
          527
        ],
        "tileVerifyPass": true,
        "LStar": 74.0,
        "CStar": 12.1,
        "nearestAnchor": "P2_ochre_sand",
        "deltaE2000": 5.03,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 187.5,
        "grainBandPass": false,
        "windowFrac": 2.0,
        "notPlasterFrac": 6.0,
        "rallyClipPct": 0.06
      }
    },
    {
      "name": "commercial",
      "index": 5,
      "surfaceClass": "facade",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "facade",
        "anchors": [
          "P6_panot_grey",
          "P2_ochre_sand"
        ],
        "tileRaw": 46.04,
        "tileRatio": 0.002,
        "tileRoll": [
          1132,
          108
        ],
        "tileVerifyPass": true,
        "LStar": 74.0,
        "CStar": 12.2,
        "nearestAnchor": "P2_ochre_sand",
        "deltaE2000": 5.16,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 62.5,
        "grainBandPass": false,
        "windowFrac": 38.2,
        "notPlasterFrac": 39.7,
        "rallyClipPct": 0.397
      }
    },
    {
      "name": "office",
      "index": 6,
      "surfaceClass": "facade",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "facade",
        "anchors": [
          "P6_panot_grey",
          "P7_bordillo_granite"
        ],
        "tileRaw": 0.43,
        "tileRatio": 0.001,
        "tileRoll": [
          1153,
          323
        ],
        "tileVerifyPass": true,
        "LStar": 74.0,
        "CStar": 12.0,
        "nearestAnchor": "P6_panot_grey",
        "deltaE2000": 5.14,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 31.2,
        "grainBandPass": false,
        "windowFrac": 40.2,
        "notPlasterFrac": 39.6,
        "rallyClipPct": 0.898
      }
    },
    {
      "name": "industrial_brick",
      "index": 7,
      "surfaceClass": "brick",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "brick",
        "anchors": [
          "P5_poblenou_brick",
          "P4_teula_clay"
        ],
        "tileRaw": 6.19,
        "tileRatio": 0.002,
        "tileRoll": [
          1216,
          714
        ],
        "tileVerifyPass": true,
        "LStar": 45.0,
        "CStar": 22.6,
        "nearestAnchor": "P5_poblenou_brick",
        "deltaE2000": 6.52,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 125.0,
        "grainBandPass": true,
        "windowFrac": 3.5,
        "notPlasterFrac": 50.9,
        "rallyClipPct": 0.187
      }
    }
  ],
  "arrays": {
    "albedo": "facade_body_albedo.ktx2",
    "normal": "facade_body_normal.ktx2",
    "layerOrder": [
      "residential_cream",
      "residential_ochre",
      "residential_rose",
      "residential_grey",
      "residential_oldtown",
      "commercial",
      "office",
      "industrial_brick"
    ]
  },
  "vram": {
    "uncompressedMiB": 85.3,
    "bc7MiB": 21.3
  }
};
