// GENERATED by tools/build-road-textures.py — do not edit by hand.
export default {
  "normalizeVersion": 2,
  "surfaces": [
    {
      "name": "asphalt_worn",
      "size": 1024,
      "spanM": 4.0,
      "note": "Worn carriageway - exposed aggregate, patching, tyre polish",
      "meanLuma": 0.10787,
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "asphalt",
        "anchor": "#4F4E4C",
        "tileRaw": 2.46,
        "tileRatio": 0.052,
        "tileRepair": "aligned (roll 952,528)",
        "tileVerifyPass": true,
        "LStar": 38.0,
        "CStar": 3.4,
        "nearestAnchor": "P8_carriageway_grey",
        "deltaE2000": 4.44,
        "gate4Pass": true,
        "normalMeanXY": 0.16,
        "normalBandPass": true,
        "normalSource": "luminance-derived (AD-1a: photoscan is the upgrade)",
        "rallyClipPct": 0.0
      }
    },
    {
      "name": "asphalt_fresh",
      "size": 1024,
      "spanM": 4.0,
      "note": "Recently laid - tight aggregate still coated in binder",
      "meanLuma": 0.10756,
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "asphalt",
        "anchor": "#4F4E4C",
        "tileRaw": 1.76,
        "tileRatio": 0.023,
        "tileRepair": "aligned (roll 512,1080)",
        "tileVerifyPass": true,
        "LStar": 38.0,
        "CStar": 2.5,
        "nearestAnchor": "P8_carriageway_grey",
        "deltaE2000": 4.78,
        "gate4Pass": true,
        "normalMeanXY": 0.16,
        "normalBandPass": true,
        "normalSource": "luminance-derived (AD-1a: photoscan is the upgrade)",
        "rallyClipPct": 0.0
      }
    },
    {
      "name": "panot",
      "size": 1024,
      "spanM": 0.4,
      "note": "Flor de Barcelona panot - 2x2 of 20 cm tiles",
      "meanLuma": 0.31577,
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "sidewalk",
        "anchor": "#B4B0A6",
        "tileRaw": 31.93,
        "tileRatio": 0.022,
        "tileRepair": "aligned (roll 496,536)",
        "tileVerifyPass": true,
        "LStar": 62.0,
        "CStar": 5.0,
        "nearestAnchor": "P6_panot_grey",
        "deltaE2000": 7.98,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "normalSource": "luminance-derived (AD-1a: photoscan is the upgrade)",
        "rallyClipPct": 0.005
      }
    }
  ]
};
