// GENERATED by tools/build-rock-atlas.py — do not edit by hand.
export default {
  "cell": 1024,
  "cols": 2,
  "rows": 2,
  "normalizeVersion": 2,
  "stones": [
    {
      "name": "collserola_schist",
      "cell": 0,
      "note": "Layered grey hillside schist - Collserola",
      "spanM": 2.0,
      "uv": [
        0.0,
        0.5,
        0.5,
        0.5
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "rock",
        "snapAlpha": 0.35,
        "tileRatio": 3.196,
        "tileVerifyPass": false,
        "LStar": 55.0,
        "CStar": 6.5,
        "nearestAnchor": "P7_bordillo_granite",
        "deltaE2000": 5.01,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "rallyClipPct": 0.082
      }
    },
    {
      "name": "montjuic_sandstone",
      "cell": 1,
      "note": "The warm quarried stone Barcelona is built from",
      "spanM": 2.0,
      "uv": [
        0.5,
        0.5,
        0.5,
        0.5
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "rock",
        "snapAlpha": 0.35,
        "tileRatio": 2.505,
        "tileVerifyPass": false,
        "LStar": 55.1,
        "CStar": 7.0,
        "nearestAnchor": "P7_bordillo_granite",
        "deltaE2000": 5.24,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "rallyClipPct": 0.668
      }
    },
    {
      "name": "limestone_lichen",
      "cell": 2,
      "note": "Weathered limestone with lichen - old walls and outcrops",
      "spanM": 2.0,
      "uv": [
        0.0,
        0.0,
        0.5,
        0.5
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "rock",
        "snapAlpha": 0.35,
        "tileRatio": 1.101,
        "tileVerifyPass": true,
        "LStar": 55.0,
        "CStar": 6.9,
        "nearestAnchor": "P7_bordillo_granite",
        "deltaE2000": 5.14,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "rallyClipPct": 0.016
      }
    }
  ]
};
