// GENERATED by tools/build-shopfront-layers.py — do not edit by hand.
export default {
  "layerWidthM": 7.0,
  "layerHeightM": 4.0,
  "width": 896,
  "height": 512,
  "texelsPerM": 128.0,
  "normalizeVersion": 2,
  "layers": [
    {
      "name": "residential_cream",
      "index": 0,
      "surfaceClass": "facade",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "facade",
        "anchors": [
          "P1_eixample_cream",
          "P2_ochre_sand"
        ],
        "tileAxis": "u",
        "tileRaw": 8.54,
        "tileRatio": 0.002,
        "tileRoll": [
          0,
          457
        ],
        "tileVerifyPass": true,
        "LStar": 22.8,
        "CStar": 7.0,
        "nearestAnchor": "P8_carriageway_grey",
        "deltaE2000": 9.53,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 125.0,
        "grainBandPass": false
      }
    },
    {
      "name": "residential_ochre",
      "index": 1,
      "surfaceClass": "facade",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "facade",
        "anchors": [
          "P2_ochre_sand",
          "P6_panot_grey"
        ],
        "tileAxis": "u",
        "tileRaw": 5.91,
        "tileRatio": 0.0,
        "tileRoll": [
          0,
          1313
        ],
        "tileVerifyPass": true,
        "LStar": 53.7,
        "CStar": 6.9,
        "nearestAnchor": "P7_bordillo_granite",
        "deltaE2000": 4.42,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 109.4,
        "grainBandPass": false
      }
    },
    {
      "name": "residential_rose",
      "index": 2,
      "surfaceClass": "facade",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "facade",
        "anchors": [
          "P3_modernisme_rose",
          "P4_teula_clay"
        ],
        "tileAxis": "u",
        "tileRaw": 0.65,
        "tileRatio": 0.646,
        "tileRoll": [
          0,
          0
        ],
        "tileVerifyPass": true,
        "LStar": 25.3,
        "CStar": 10.1,
        "nearestAnchor": "P8_carriageway_grey",
        "deltaE2000": 10.25,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 78.1,
        "grainBandPass": false
      }
    },
    {
      "name": "residential_grey",
      "index": 3,
      "surfaceClass": "facade",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "facade",
        "anchors": [
          "P6_panot_grey",
          "P7_bordillo_granite"
        ],
        "tileAxis": "u",
        "tileRaw": 4.83,
        "tileRatio": 0.0,
        "tileRoll": [
          0,
          1154
        ],
        "tileVerifyPass": true,
        "LStar": 58.1,
        "CStar": 3.0,
        "nearestAnchor": "P7_bordillo_granite",
        "deltaE2000": 6.57,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 109.4,
        "grainBandPass": false
      }
    },
    {
      "name": "residential_oldtown",
      "index": 4,
      "surfaceClass": "facade",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "facade",
        "anchors": [
          "P2_ochre_sand",
          "P1_eixample_cream"
        ],
        "tileAxis": "u",
        "tileRaw": 7.48,
        "tileRatio": 0.0,
        "tileRoll": [
          0,
          317
        ],
        "tileVerifyPass": true,
        "LStar": 48.2,
        "CStar": 14.1,
        "nearestAnchor": "P7_bordillo_granite",
        "deltaE2000": 9.27,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 156.2,
        "grainBandPass": false
      }
    },
    {
      "name": "commercial",
      "index": 5,
      "surfaceClass": "facade",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "facade",
        "anchors": [
          "P6_panot_grey",
          "P7_bordillo_granite"
        ],
        "tileAxis": "u",
        "tileRaw": 0.89,
        "tileRatio": 0.891,
        "tileRoll": [
          0,
          0
        ],
        "tileVerifyPass": true,
        "LStar": 29.1,
        "CStar": 1.7,
        "nearestAnchor": "P8_carriageway_grey",
        "deltaE2000": 3.52,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 109.4,
        "grainBandPass": false
      }
    },
    {
      "name": "office",
      "index": 6,
      "surfaceClass": "facade",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "facade",
        "anchors": [
          "P6_panot_grey",
          "P1_eixample_cream"
        ],
        "tileAxis": "u",
        "tileRaw": 0.0,
        "tileRatio": 0.001,
        "tileRoll": [
          0,
          0
        ],
        "tileVerifyPass": true,
        "LStar": 48.2,
        "CStar": 3.4,
        "nearestAnchor": "P7_bordillo_granite",
        "deltaE2000": 3.24,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 171.9,
        "grainBandPass": false
      }
    },
    {
      "name": "industrial_brick",
      "index": 7,
      "surfaceClass": "brick",
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "surfaceClass": "brick",
        "anchors": [
          "P5_poblenou_brick",
          "P4_teula_clay"
        ],
        "tileAxis": "u",
        "tileRaw": 1.61,
        "tileRatio": 0.0,
        "tileRoll": [
          0,
          187
        ],
        "tileVerifyPass": true,
        "LStar": 33.5,
        "CStar": 9.9,
        "nearestAnchor": "P8_carriageway_grey",
        "deltaE2000": 9.07,
        "gate4Pass": true,
        "normalMeanXY": 0.25,
        "normalBandPass": true,
        "grainMM": 125.0,
        "grainBandPass": true
      }
    }
  ],
  "arrays": {
    "albedo": "facade_ground_albedo.ktx2",
    "normal": "facade_ground_normal.ktx2",
    "layerOrder": [
      "residential_cream",
      "residential_ochre",
      "residential_rose",
      "residential_grey",
      "residential_oldtown",
      "commercial",
      "office",
      "industrial_brick"
    ]
  }
};
