// GENERATED by tools/build-sky-textures.py — do not edit by hand.
export default {
  "width": 2048,
  "height": 1024,
  "cloudAltM": 1200.0,
  "layers": [
    {
      "name": "sky_clouds_day",
      "coverage": 16.5,
      "seam": 0.000175
    },
    {
      "name": "sky_clouds_night",
      "coverage": 16.5,
      "seam": 0.000175
    }
  ]
};
