// GENERATED by tools/build-tree-atlas.py — do not edit by hand.
// Re-run the tool after changing SPECIES or any source plate.
export default {
  "cell": 1024,
  "cols": 3,
  "rows": 2,
  "normalizeVersion": 2,
  "species": [
    {
      "name": "plane_pollarded",
      "cell": 0,
      "note": "Platanus x acerifolia, pollarded - the signature Barcelona street tree",
      "heightM": 12.0,
      "canopyM": 9.0,
      "uv": [
        0.0,
        0.5,
        0.333333,
        0.5
      ],
      "trunkBase": [
        0.5,
        0.9883
      ],
      "aspect": 1.0081,
      "contentUV": [
        0.003906,
        0.505859,
        0.325521,
        0.484375
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "foliage_leaf",
        "anchor": [
          "#6E7A55",
          "#2F5C77"
        ],
        "snapAlpha": 0.35,
        "LStar": 45.0,
        "CStar": 20.5,
        "nearestAnchor": "P9_platanus_green",
        "deltaE2000": 6.0,
        "gate4Pass": true,
        "normalMeanXY": 0.275,
        "normalBandPass": true,
        "rallyClipPct": 2.846
      }
    },
    {
      "name": "tipuana",
      "cell": 1,
      "note": "Tipuana tipu - broad flat crown, second most common",
      "heightM": 12.0,
      "canopyM": 14.0,
      "uv": [
        0.333333,
        0.5,
        0.333333,
        0.5
      ],
      "trunkBase": [
        0.5,
        0.9883
      ],
      "aspect": 1.3072,
      "contentUV": [
        0.33724,
        0.505859,
        0.325521,
        0.373535
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "foliage_leaf",
        "anchor": [
          "#6E7A55",
          "#2F5C77"
        ],
        "snapAlpha": 0.35,
        "LStar": 45.0,
        "CStar": 20.5,
        "nearestAnchor": "P9_platanus_green",
        "deltaE2000": 6.78,
        "gate4Pass": true,
        "normalMeanXY": 0.275,
        "normalBandPass": true,
        "rallyClipPct": 0.0
      }
    },
    {
      "name": "celtis",
      "cell": 2,
      "note": "Celtis australis - rounded dome, side streets",
      "heightM": 12.0,
      "canopyM": 10.0,
      "uv": [
        0.666667,
        0.5,
        0.333333,
        0.5
      ],
      "trunkBase": [
        0.5,
        0.9883
      ],
      "aspect": 0.97,
      "contentUV": [
        0.675456,
        0.505859,
        0.315755,
        0.488281
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "foliage_leaf",
        "anchor": [
          "#6E7A55",
          "#2F5C77"
        ],
        "snapAlpha": 0.35,
        "LStar": 45.0,
        "CStar": 20.6,
        "nearestAnchor": "P9_platanus_green",
        "deltaE2000": 4.9,
        "gate4Pass": true,
        "normalMeanXY": 0.275,
        "normalBandPass": true,
        "rallyClipPct": 1.484
      }
    },
    {
      "name": "washingtonia",
      "cell": 3,
      "note": "Washingtonia robusta - coast and Passeig",
      "heightM": 15.0,
      "canopyM": 4.5,
      "uv": [
        0.0,
        0.0,
        0.333333,
        0.5
      ],
      "trunkBase": [
        0.5,
        0.9883
      ],
      "aspect": 0.614,
      "contentUV": [
        0.066732,
        0.005859,
        0.19987,
        0.488281
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "foliage_leaf",
        "anchor": [
          "#6E7A55",
          "#2F5C77"
        ],
        "snapAlpha": 0.35,
        "LStar": 45.0,
        "CStar": 20.1,
        "nearestAnchor": "P9_platanus_green",
        "deltaE2000": 7.14,
        "gate4Pass": true,
        "normalMeanXY": 0.275,
        "normalBandPass": true,
        "rallyClipPct": 8.297
      }
    },
    {
      "name": "jacaranda",
      "cell": 4,
      "note": "Jacaranda mimosifolia in flower - seasonal accent",
      "heightM": 10.0,
      "canopyM": 8.0,
      "uv": [
        0.333333,
        0.0,
        0.333333,
        0.5
      ],
      "trunkBase": [
        0.5,
        0.9883
      ],
      "aspect": 0.98,
      "contentUV": [
        0.340495,
        0.005859,
        0.31901,
        0.488281
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "foliage_leaf",
        "anchor": [
          "#6E7A55",
          "#2F5C77"
        ],
        "snapAlpha": 0.35,
        "LStar": 45.0,
        "CStar": 20.5,
        "nearestAnchor": "P10_mediterrani_blue",
        "deltaE2000": 17.01,
        "gate4Pass": false,
        "normalMeanXY": 0.275,
        "normalBandPass": true,
        "rallyClipPct": 0.032
      }
    },
    {
      "name": "orange_bitter",
      "cell": 5,
      "note": "Citrus x aurantium - plazas and narrow streets",
      "heightM": 5.0,
      "canopyM": 4.5,
      "uv": [
        0.666667,
        0.0,
        0.333333,
        0.5
      ],
      "trunkBase": [
        0.5,
        0.9883
      ],
      "aspect": 0.96,
      "contentUV": [
        0.677083,
        0.005859,
        0.3125,
        0.488281
      ],
      "normalize": {
        "version": 2,
        "sourceType": "ai",
        "k": 0.35,
        "surfaceClass": "foliage_leaf",
        "anchor": [
          "#6E7A55",
          "#2F5C77"
        ],
        "snapAlpha": 0.35,
        "LStar": 45.0,
        "CStar": 20.5,
        "nearestAnchor": "P9_platanus_green",
        "deltaE2000": 4.9,
        "gate4Pass": true,
        "normalMeanXY": 0.275,
        "normalBandPass": true,
        "rallyClipPct": 2.382
      }
    }
  ]
};
