/**
 * signQuads.js — the geometry side of the sign pool. v3 P4-11.
 *
 * Pure arithmetic on typed arrays: no three.js, no WebGL, so the UV packing — the part that is
 * silently wrong when it is wrong — is testable in node. `signPool.js` wraps these into
 * BufferGeometry.
 *
 * ── WHY TWO MECHANISMS AND NOT ONE ─────────────────────────────────────────────────────────────
 *
 * The ticket says "per-instance aUvOffset" for everything. That is right for one of the two cases
 * and needless for the other, and this codebase already ships a working example of each:
 *
 *   SIGN FACES are a fixed set — 18 cells, known at build time. So each cell gets its own quad with
 *   its UVs BAKED IN, and they go into a `BatchedMesh` exactly as `createVegPool` does: one draw
 *   call, per-instance geometry id, per-instance colour via setColorAt. No custom attribute, no
 *   shader edit, nothing new to get wrong.
 *
 *   TEXT QUADS cannot work that way. A street name's cell is allocated at RUNTIME by the bounded
 *   text page and changes as you drive, so the UV must be per-instance. That is an InstancedMesh
 *   with an `aUvOffset` attribute — the pattern `shopSignRenderer.js` already ships, and therefore
 *   proven in this renderer rather than assumed.
 *
 * Choosing the simpler mechanism where it suffices is the point: the fixed set is most of the signs
 * in the city and it costs no shader surgery at all.
 */

/**
 * A unit quad for one atlas cell, with the cell's UVs baked in.
 *
 * Faces +Z, spans [-w/2, w/2] x [0, h] — origin at the BOTTOM CENTRE, because a sign is positioned
 * by where its post meets the ground, not by its middle. Getting that wrong buries half of every
 * sign in the pavement, and it reads as a height bug rather than an origin bug.
 *
 * @param {{uv:number[]}} cell  a manifest entry from signAtlasCells.js
 * @param {number} w  width in metres
 * @param {number} h  height in metres
 */
export function cellQuad(cell, w, h) {
  const [u0, v0, u1, v1] = cell.uv;
  const hw = w / 2;
  return {
    position: new Float32Array([
      -hw, 0, 0, hw, 0, 0, hw, h, 0, -hw, h, 0,
    ]),
    normal: new Float32Array([
      0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
    ]),
    // v0 is the BOTTOM of the cell in the manifest's bottom-up V, so it pairs with y = 0.
    uv: new Float32Array([
      u0, v0, u1, v0, u1, v1, u0, v1,
    ]),
    index: new Uint16Array([0, 1, 2, 0, 2, 3]),
  };
}

/**
 * Pack one instance's text-page rect into the four floats an `aUvOffset` attribute carries.
 *
 * ⚠ SCALE + OFFSET, not the raw rect. The shader does `uv * scale + offset`, so a mesh whose base
 * UVs are the unit square lands on the cell with one multiply-add. Passing the rect instead forces
 * every consumer to do the subtraction itself, which is how two call sites end up disagreeing about
 * whether v is measured from the top.
 */
export function packUvOffset(rect, out, i) {
  out[i * 4 + 0] = rect.u1 - rect.u0;   // scale u
  out[i * 4 + 1] = rect.v1 - rect.v0;   // scale v
  out[i * 4 + 2] = rect.u0;             // offset u
  out[i * 4 + 3] = rect.v0;             // offset v
  return out;
}

/** Apply what the shader would, so a test can check the packing round-trips. */
export function applyUvOffset(packed, i, u, v) {
  return [u * packed[i * 4 + 0] + packed[i * 4 + 2],
    v * packed[i * 4 + 1] + packed[i * 4 + 3]];
}

/**
 * Index every cell by name once, so a renderer never does a linear scan per sign.
 *
 * Throws on an unknown name rather than returning undefined: a missing cell would otherwise sample
 * whatever sits at UV (0,0) and draw the wrong sign with complete confidence — the failure mode
 * that makes an atlas bug look like an art bug.
 */
export function indexCells(manifest) {
  const byName = new Map();
  for (const c of manifest.cells) byName.set(c.name, c);
  return {
    get(name) {
      const c = byName.get(name);
      if (!c) {
        throw new Error(`signAtlas: no cell named '${name}' — cells are generated by `
          + 'tools/build-sign-atlas.py and their ORDER is part of the contract');
      }
      return c;
    },
    has: (name) => byName.has(name),
    get size() { return byName.size; },
  };
}
