// GENERATED by tools/build-sign-atlas.py — do not edit by hand.
// Cell ORDER is part of the contract: appending is safe, reordering is not.
export default {
  "cell": 256,
  "cols": 8,
  "rows": 4,
  "texture": "/textures/signage/sign_atlas_albedo.ktx2",
  "cells": [
    {
      "name": "plate_white",
      "cell": 0,
      "note": "blank retroreflective panel \u2014 the text page draws the street name onto this",
      "sizeM": 1.2,
      "mount": "post",
      "uv": [
        0.0,
        0.75,
        0.125,
        1.0
      ]
    },
    {
      "name": "plate_blue",
      "cell": 1,
      "note": "blue urban direction panel",
      "sizeM": 1.2,
      "mount": "post",
      "uv": [
        0.125,
        0.75,
        0.25,
        1.0
      ]
    },
    {
      "name": "speed_20",
      "cell": 2,
      "note": "zona 30 side streets and school zones",
      "sizeM": 0.9,
      "mount": "post",
      "uv": [
        0.25,
        0.75,
        0.375,
        1.0
      ]
    },
    {
      "name": "speed_30",
      "cell": 3,
      "note": "the Barcelona default \u2014 most of the city",
      "sizeM": 0.9,
      "mount": "post",
      "uv": [
        0.375,
        0.75,
        0.5,
        1.0
      ]
    },
    {
      "name": "speed_40",
      "cell": 4,
      "note": "",
      "sizeM": 0.9,
      "mount": "post",
      "uv": [
        0.5,
        0.75,
        0.625,
        1.0
      ]
    },
    {
      "name": "speed_50",
      "cell": 5,
      "note": "primary/secondary in town",
      "sizeM": 0.9,
      "mount": "post",
      "uv": [
        0.625,
        0.75,
        0.75,
        1.0
      ]
    },
    {
      "name": "speed_60",
      "cell": 6,
      "note": "",
      "sizeM": 0.9,
      "mount": "post",
      "uv": [
        0.75,
        0.75,
        0.875,
        1.0
      ]
    },
    {
      "name": "speed_80",
      "cell": 7,
      "note": "ronda / autovia",
      "sizeM": 0.9,
      "mount": "post",
      "uv": [
        0.875,
        0.75,
        1.0,
        1.0
      ]
    },
    {
      "name": "stop",
      "cell": 8,
      "note": "",
      "sizeM": 0.9,
      "mount": "post",
      "uv": [
        0.0,
        0.5,
        0.125,
        0.75
      ]
    },
    {
      "name": "yield",
      "cell": 9,
      "note": "ceda el paso",
      "sizeM": 0.9,
      "mount": "post",
      "uv": [
        0.125,
        0.5,
        0.25,
        0.75
      ]
    },
    {
      "name": "no_entry",
      "cell": 10,
      "note": "direccion prohibida",
      "sizeM": 0.9,
      "mount": "post",
      "uv": [
        0.25,
        0.5,
        0.375,
        0.75
      ]
    },
    {
      "name": "arrow_straight",
      "cell": 11,
      "note": "lane pictogram, painted on asphalt",
      "sizeM": 3.5,
      "mount": "road",
      "uv": [
        0.375,
        0.5,
        0.5,
        0.75
      ]
    },
    {
      "name": "arrow_left",
      "cell": 12,
      "note": "",
      "sizeM": 3.5,
      "mount": "road",
      "uv": [
        0.5,
        0.5,
        0.625,
        0.75
      ]
    },
    {
      "name": "arrow_right",
      "cell": 13,
      "note": "",
      "sizeM": 3.5,
      "mount": "road",
      "uv": [
        0.625,
        0.5,
        0.75,
        0.75
      ]
    },
    {
      "name": "arrow_straight_left",
      "cell": 14,
      "note": "",
      "sizeM": 3.5,
      "mount": "road",
      "uv": [
        0.75,
        0.5,
        0.875,
        0.75
      ]
    },
    {
      "name": "arrow_straight_right",
      "cell": 15,
      "note": "",
      "sizeM": 3.5,
      "mount": "road",
      "uv": [
        0.875,
        0.5,
        1.0,
        0.75
      ]
    },
    {
      "name": "pharmacy_cross",
      "cell": 16,
      "note": "P4-13 night set \u2014 emissive",
      "sizeM": 0.8,
      "mount": "post",
      "uv": [
        0.0,
        0.25,
        0.125,
        0.5
      ]
    },
    {
      "name": "metro_roundel",
      "cell": 17,
      "note": "P4-13 night set \u2014 emissive",
      "sizeM": 0.85,
      "mount": "post",
      "uv": [
        0.125,
        0.25,
        0.25,
        0.5
      ]
    }
  ]
};
